site_name: Figmagen
site_description: Generate tokens from Figma easily for multiple languages or frameworks
site_author: Stuart
remote_branch: gh-pages

repo_name: figmagen
repo_url: https://github.com/StuartApp/figmagen

copyright: 'Copyright &copy; 2022 Stuart'

theme:
  name: 'material'
  language: 'en'
  favicon: 'assets/favicon.png'
  logo: 'assets/logo.svg'
  font:
    text: 'Fira Sans'
    code: 'JetBrains Mono'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: 'white'
      accent: 'white'
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: 'indigo'
      accent: 'light blue'
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

nav:
  - Overview: index.md

plugins:
  - search

markdown_extensions:
  - admonition
  - smarty
  - codehilite:
      guess_lang: false
      linenums: True
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - tables

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/StuartApp
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Stuart_Delivery

extra_css:
  - css/all.css
