package com.stuart.figmagen.models

/**
 * The output that are being to be generated by `Figmagen`
 *
 * @property path the file path
 * @property content the file content
 */
public data class TaskFile(val path: String, val content: String)
